apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "whoami.fullname" . }}
  labels:
    app: {{ include "whoami.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "whoami.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "whoami.name" . }}
    spec:
      containers:
        - name: whoami
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          {{- if .Values.resources }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}